### 1. 연결 확인
GET http://localhost:9200/

### 2. 모든 인덱스(테이블) 목록 확인
GET http://localhost:9200/_cat/indices?v

###
GET http://localhost:9200/user_profiles/_search

### 3. 'posts' 인덱스 데이터 10개 조회
GET http://localhost:9200/posts/_search
Content-Type: application/json

{
  "query": { "match_all": {} },
  "size": 2
}

### 4. 게시글의 제목과 임베딩 벡터 존재 여부 확인
GET http://localhost:9200/posts/_search
Content-Type: application/json

{
  "size": 1,
  "_source": ["postId", "title", "titleEmbedding"],
  "query": {
    "match_all": {}
  }
}

### 5. 게시글 전체 인덱싱 삭제
DELETE http://localhost:9200/posts

### 일반 검색 테스트
GET http://localhost:8080/api/v1/search/general?query=spring
Content-Type: application/json

### 개인화 검색 테스트
GET http://localhost:8080/api/v1/search/personalized?query=도커&userId=1
Content-Type: application/json